Feat: GPX-670, Documentation and Tests
gepaplexx/multena-proxy pull request #50
Opened 2023-06-09 07:40 UTC by Lucostus

Added Documentation for almost all functions
Added Tests for most functions

2023-06-09 08:11 UTC, tomeindl commented on init.go
> +// doInit carries out the main initialization routine for the Proxy. It logs the commit information,
heißt jetzt init oder

2023-06-09 11:42 UTC, tomeindl approved these changes

2023-06-12 05:48 UTC, fhochleitner approved these changes
nur kleinigkeiten.

2023-06-12 05:48 UTC, fhochleitner commented on enforcer_promql.go
> +		Logger.Debug("error",
errors würd ich nicht auf debug loggen

2023-06-12 05:48 UTC, fhochleitner commented on init.go
> +		Addr:                 Cfg.Db.Host + ":" + fmt.Sprint(Cfg.Db.Port),
wahrscheinlich wäre ein fmt.Printf schöner zum zusammenbauen der connection url.

2023-06-12 05:49 UTC, fhochleitner commented
und ein test scheint schiefzugehen :)

2023-06-12 06:49 UTC, ShahinMahmody approved these changes

2023-06-12 08:38 UTC, hwirnsberger requested changes
Bitte die besprochenen Änderungen einpflegen

2023-06-12 13:25 UTC, merged